### ISSUE TITLE
windows 10 UWP

### ISSUE THREAD

**Issue by fpsqdb** [kiewic/MediaElementWithHttpClient#3]
On windows 10 1607 have a new [MediaPlayerElement](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.mediaplayerelement). So need use [Windows.Media.Core.MediaSource.CreateFromStream](https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.core.mediasource.createfromstream) method to create a media source, but it will need HttpRandomAccessStream implement the [CloneStream](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.streams.irandomaccessstream.clonestream) method.

**Comment by kiewic** [comment]
Do you mean this project is broken in Windows 1607 without implementing `CloneStream`?

**Comment by fpsqdb** [comment]
Yes if use  [MediaPlayerElement](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.mediaplayerelement)

**Comment by kiewic** [comment]
According to the MSDN [Adaptive streaming](https://msdn.microsoft.com/en-us/windows/uwp/audio-video-camera/adaptive-streaming) article, there is a new component called `AdaptiveMediaSource` which allows to pass setting from a `HttpClient` to a `MediaPlayerElement`.

I think that should be equivalent. But let me know if it isn`t, and I will see what I can do.

Thank you!

**Comment by fpsqdb** [comment]
It only support Http Live Streaming (HLS) and Dynamic Adaptive Streaming over HTTP (DASH)

**Comment by kiewic** [comment]
@fpsqdb,

I got some time today to investigate the issue. The solution turned to be very simple:

```
public IRandomAccessStream CloneStream()
{
    // If there is only one MediaPlayerElement using the stream, it is safe to return itself.
    return this;
}
```

For clarity (`MediaElement` vs `MediaPlayerElement`), I have started a new repository with the solution:

https://github.com/kiewic/MediaPlayerElementWithHttpClient

Let me know if you have any concern, and thanks for reporting the issue!
